# Generated by Django 4.2 on 2023-05-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='Blog keywords', max_length=100),
            preserve_default=False,
        ),
    ]
